# Generated by Django 2.1.1 on 2019-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdInfo',
            field=models.TextField(),
        ),
    ]
