# Generated by Django 2.1.1 on 2019-02-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_address'),
        ('Shop', '0002_auto_20190219_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('pnum', models.IntegerField()),
                ('standard', models.CharField(max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cat', to='Shop.Product')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_cat', to='User.UserInfo')),
            ],
        ),
    ]
