# Generated by Django 2.1.1 on 2019-02-25 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_address'),
        ('Shop', '0005_auto_20190225_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('pnum', models.IntegerField()),
                ('sumprice', models.CharField(max_length=64)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cat', to='Shop.Product')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_cat', to='User.UserInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='userinfo',
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
