# Generated by Django 2.1.1 on 2019-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20190226_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
