# Generated by Django 2.1.1 on 2019-02-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20190226_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cartid', models.IntegerField()),
            ],
        ),
    ]
