# Generated by Django 2.1.1 on 2019-02-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_paycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCart2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carttopay', to='Shop.Cart')),
            ],
        ),
        migrations.DeleteModel(
            name='Paycart',
        ),
    ]
