# Generated by Django 2.1.1 on 2019-02-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20190227_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('ordernum', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=30)),
                ('productlist', models.TextField()),
                ('pricelist', models.TextField()),
                ('allprice', models.FloatField()),
                ('allpnum', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
