# Generated by Django 2.1.1 on 2019-02-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_order1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order1',
            new_name='ORDER',
        ),
    ]
