# Generated by Django 2.1.1 on 2019-02-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_auto_20190227_1008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ORDER',
            new_name='ORDER1',
        ),
    ]
