# Generated by Django 2.1.1 on 2019-02-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_auto_20190227_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORDER1',
        ),
    ]
