# Generated by Django 2.1.1 on 2019-02-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayCart2',
            new_name='PayCart',
        ),
    ]
