# Generated by Django 2.1.1 on 2019-02-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_address'),
        ('Shop', '0015_auto_20190227_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernum', models.CharField(max_length=32)),
                ('allprice', models.FloatField()),
                ('allpnum', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='Shop.Product')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_order', to='User.UserInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
