# Generated by Django 2.1.1 on 2019-01-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.CharField(default='', max_length=15)),
                ('password_hash', models.TextField()),
            ],
        ),
    ]
