# Generated by Django 2.1.1 on 2019-02-01 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20190127_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=128)),
                ('get_name', models.CharField(max_length=128)),
                ('get_phone', models.CharField(max_length=128)),
                ('get_code', models.CharField(max_length=128)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_address', to='User.UserInfo')),
            ],
        ),
    ]
