# Generated by Django 2.1.1 on 2019-02-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_imagerd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageRd',
            new_name='ImageRecord',
        ),
    ]
